version: "3.7"

services:
  mysql-dev:
    container_name: mysql_dev_ordering
    image: "mysql:latest"
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - dev
    environment:
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=ordering
    ports:
      - 3326:3306

networks:
  dev:
    driver: bridge
