version: "3.7"

services:
  mysql-test:
    image: "mysql:latest"
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_USER=test
      - MYSQL_PASSWORD=test
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=test
    ports:
      - 3316:3306
    expose:
      - "3316"
