// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	context "context"

	models "github.com/masterraf21/reksti-ordering-backend/models"
	mock "github.com/stretchr/testify/mock"
)

// MenuTypeRepository is an autogenerated mock type for the MenuTypeRepository type
type MenuTypeRepository struct {
	mock.Mock
}

// BulkInsert provides a mock function with given fields: ctx, MenuType
func (_m *MenuTypeRepository) BulkInsert(ctx context.Context, MenuType []models.MenuType) error {
	ret := _m.Called(ctx, MenuType)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []models.MenuType) error); ok {
		r0 = rf(ctx, MenuType)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteByID provides a mock function with given fields: ctx, mtypeID
func (_m *MenuTypeRepository) DeleteByID(ctx context.Context, mtypeID uint32) error {
	ret := _m.Called(ctx, mtypeID)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint32) error); ok {
		r0 = rf(ctx, mtypeID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAll provides a mock function with given fields:
func (_m *MenuTypeRepository) GetAll() ([]models.MenuType, error) {
	ret := _m.Called()

	var r0 []models.MenuType
	if rf, ok := ret.Get(0).(func() []models.MenuType); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.MenuType)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByID provides a mock function with given fields: menuTypeID
func (_m *MenuTypeRepository) GetByID(menuTypeID uint32) (*models.MenuType, error) {
	ret := _m.Called(menuTypeID)

	var r0 *models.MenuType
	if rf, ok := ret.Get(0).(func(uint32) *models.MenuType); ok {
		r0 = rf(menuTypeID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.MenuType)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(uint32) error); ok {
		r1 = rf(menuTypeID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Store provides a mock function with given fields: ctx, ord
func (_m *MenuTypeRepository) Store(ctx context.Context, ord *models.MenuType) (uint32, error) {
	ret := _m.Called(ctx, ord)

	var r0 uint32
	if rf, ok := ret.Get(0).(func(context.Context, *models.MenuType) uint32); ok {
		r0 = rf(ctx, ord)
	} else {
		r0 = ret.Get(0).(uint32)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *models.MenuType) error); ok {
		r1 = rf(ctx, ord)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateByID provides a mock function with given fields: ctx, menuTypeID, order
func (_m *MenuTypeRepository) UpdateByID(ctx context.Context, menuTypeID uint32, order *models.MenuType) error {
	ret := _m.Called(ctx, menuTypeID, order)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint32, *models.MenuType) error); ok {
		r0 = rf(ctx, menuTypeID, order)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
