// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	context "context"

	models "github.com/masterraf21/reksti-ordering-backend/models"
	mock "github.com/stretchr/testify/mock"
)

// RatingRepository is an autogenerated mock type for the RatingRepository type
type RatingRepository struct {
	mock.Mock
}

// DeleteById provides a mock function with given fields: ratingID
func (_m *RatingRepository) DeleteById(ratingID uint32) error {
	ret := _m.Called(ratingID)

	var r0 error
	if rf, ok := ret.Get(0).(func(uint32) error); ok {
		r0 = rf(ratingID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAll provides a mock function with given fields:
func (_m *RatingRepository) GetAll() ([]models.Rating, error) {
	ret := _m.Called()

	var r0 []models.Rating
	if rf, ok := ret.Get(0).(func() []models.Rating); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Rating)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetById provides a mock function with given fields: ratingID
func (_m *RatingRepository) GetById(ratingID uint32) (*models.Rating, error) {
	ret := _m.Called(ratingID)

	var r0 *models.Rating
	if rf, ok := ret.Get(0).(func(uint32) *models.Rating); ok {
		r0 = rf(ratingID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Rating)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(uint32) error); ok {
		r1 = rf(ratingID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Store provides a mock function with given fields: rating
func (_m *RatingRepository) Store(rating *models.Rating) error {
	ret := _m.Called(rating)

	var r0 error
	if rf, ok := ret.Get(0).(func(*models.Rating) error); ok {
		r0 = rf(rating)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Update provides a mock function with given fields: ctx, rating
func (_m *RatingRepository) Update(ctx context.Context, rating *models.Rating) error {
	ret := _m.Called(ctx, rating)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.Rating) error); ok {
		r0 = rf(ctx, rating)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
